databases:
  - name: s1f102501350-django-team-workflow-db
    plan: free
    databaseName: s1f102501350_django_team_workflow
    user: s1f102501350_django_team

services:
  - type: web
    name: s1f102501350-django-team-workflow
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: s1f102501350-django-team-workflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4
